version: '3'
services:
  app:
    image: app:latest
    build: .
    environment: 
      - FLASK_APP=app
    volumes:
      - ./dash-board:/project/dash-board
    ports:
      - 8080:8080
    command: python run.py
    